//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaShop.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HexaShop.Common.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه دسترسی به این صفحه را ندارید..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی با موفقیت اضافه شد..
        /// </summary>
        public static string CategoryAdded {
            get {
                return ResourceManager.GetString("CategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات دسته بندی با موفقیت ویرایش شد..
        /// </summary>
        public static string CategoryEdited {
            get {
                return ResourceManager.GetString("CategoryEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی یافت نشد..
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر {0} شد..
        /// </summary>
        public static string ChangeUserActivity {
            get {
                return ResourceManager.GetString("ChangeUserActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این ایمیل قبلا در دیتا بیس ثبت نام کرده..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل آپلود شد.
        /// </summary>
        public static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند فایل معتبر نمی باشد.
        /// </summary>
        public static string InValidFileExtension {
            get {
                return ResourceManager.GetString("InValidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات نادرست است..
        /// </summary>
        public static string InValidInformation {
            get {
                return ResourceManager.GetString("InValidInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز اشتباه است..
        /// </summary>
        public static string InValidPassword {
            get {
                return ResourceManager.GetString("InValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد عکس های اصلی یک محصول نمی تواند از یک عدد بیشتر باشد..
        /// </summary>
        public static string MainImageIsMoreThanOne {
            get {
                return ResourceManager.GetString("MainImageIsMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی والد یاقت نشد..
        /// </summary>
        public static string ParentCategoryNotFound {
            get {
                return ResourceManager.GetString("ParentCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول با موفقیت اضافه شد..
        /// </summary>
        public static string ProductAdded {
            get {
                return ResourceManager.GetString("ProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول یافت نشد..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ورود به حساب کاربری با موفقیت انجام شد..
        /// </summary>
        public static string SuccessfulSignIn {
            get {
                return ResourceManager.GetString("SuccessfulSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر با موفقیت ایجاد شد..
        /// </summary>
        public static string UserCreatedSuccessfuly {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر غیر فعال است..
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر با این نام کاربری یافت نشد..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
